### ISSUE TITLE
Rastermap in Suite2p GUI are different from results in matlab and python rastermap code

### ISSUE THREAD

**Issue by fangyue1992** [MouseLand/rastermap#10]
Thanks for developing rastermap function! What I want is to output the neuron sort number of the rastermap in Suite2p. I tried 2 ways, matlab and python code, buy both get results different from that from Suite2p GUI, while I set them the same parameters. I looked for the Suite2p python code for the parameters and I set it the same when I direct run python or matlab code, but the results are different as the 3 attached pictures (left to right: suite2p, python, matlab). 
def compute_map(self):
        ops = {'n_components': 1, 'n_X': 100, 'alpha': 1., 'K': 1.,
                    'nPC': 200, 'constraints': 2, 'annealing': True, 'init': 'pca',
                    'start_time': 0, 'end_time': -1}
And I also tried run mapping_new, mapping_old, mapping_inc, none of them can get the same result of suite2p GUI. So I want to ask what might be the reason? hope to hear advice. Thanks!
![image](https://user-images.githubusercontent.com/52596746/120111123-41a38e80-c1a3-11eb-8e6b-afbdc5b5ba9d.png)
![image](https://user-images.githubusercontent.com/52596746/120111189-8e876500-c1a3-11eb-9ae1-8273c4c4364d.png)
![image](https://user-images.githubusercontent.com/52596746/120111330-18cfc900-c1a4-11eb-99d6-c32f7c2a66b9.png)

**Comment by carsen-stringer** [comment]
this should now be resolved with the upgrade
