### ISSUE TITLE
ModuleNotFoundError: No module named 'rastermap.mapping'

### ISSUE THREAD

**Issue by Shilpadkumar** [MouseLand/rastermap#18]
Installation of Suite2p goes through but I cannot run Suite2p with 'python -m suite2p'. It reports an error 'ModuleNotFoundError: No module named 'rastermap.mapping''. I also independently installed Rastermap dependency but it still fails to launch suite2p. Is this due to the recent update on the package? 

Could you please provide me with any leads to fix this? Thank you!

**Comment by rishachakraborty** [comment]
Hello! It might help to open the visualize.py file in the suite2p/gui folder and change the line containing the import rastermap.mapping command to import rastermap. I was able to launch suite2p with this fix.

**Comment by Shilpadkumar** [comment]
Hi Risha,

Thank you! That worked for me too. I appreciate your help!


Best Regards,

Shilpa Dilipkumar, Ph.D.

Microscopy CoRE, Icahn School of Medicine at Mount Sinai.

Annenberg 18-250.

Microscopy CoRE: ext 212-241-0400; int x40400



CoRE Link: Become a Trained User<https://forms.office.com/Pages/ResponsePage.aspx?id=YZ3odw9XsEO55GNPRi40uPsO3_YkdJRGrN_MLlNfuYNUMzZCNFNQMUs1MUpGQ0s3VVdTSERMNUxZQiQlQCN0PWcu>

CoRE Link: <https://drive.google.com/file/d/10j1pHX8LHiJLhVu88BdSrrYBsVuEwS12/view> Connect to the Hive Server<https://drive.google.com/file/d/10j1pHX8LHiJLhVu88BdSrrYBsVuEwS12/view>

CoRE Link: Create a HIVE account<https://forms.office.com/Pages/ResponsePage.aspx?id=YZ3odw9XsEO55GNPRi40uPsO3_YkdJRGrN_MLlNfuYNURjRMVjBQT0xFUkRZRThBN1NINTAwNUsxNSQlQCN0PWcu>

CoRE Link: Publication Form<https://urldefense.proofpoint.com/v2/url?u=https-3A__forms.office.com_Pages_ResponsePage.aspx-3Fid-3DYZ3odw9XsEO55GNPRi40uGhL-2DImza2RLlTrsCUylbTZUMk4yMFFSRzI3VVNLVUlOMllFMkdOR1JOSS4u&d=DwMFaQ&c=shNJtf5dKgNcPZ6Yh64b-ALLUrcfR-4CCQkZVKC8w3o&r=BKZ_A33N7q29AKt8sTVW-Q5YuHldU8punNxZs8z0Xig&m=GfYG31p9ZTOA42rwwA5X-FW0rQlaMOSibuP3XPzjpdQ6SRJJTua_vhHzCW97lGh1&s=s0b9LqPhrwDPBN2YI2GVsw9YjpBY6fREoyaVzTLNoEA&e=>



Real-time support: 646-481-3753

________________________________
