### ISSUE TITLE
Error loading data: can only convert an array of size 1 to a Python scalar

### ISSUE THREAD

**Issue by vncntprvst** [MouseLand/rastermap#19]
Hi,
I'm testing the latest version of rastermap (version 0.9.3 installed with `pip install rastermap[gui]` in a new environment).
When loading a `spks.npy` generated by Suite2P, from the rastermap GUI's menu, I'm getting this error:
```
Traceback (most recent call last):
  File "C:\Users\pseud\anaconda3\envs\rastermap\lib\site-packages\rastermap\gui\menus.py", line 20, in <lambda>
    loadMat.triggered.connect(lambda: io.load_mat(parent, name=None))
  File "C:\Users\pseud\anaconda3\envs\rastermap\lib\site-packages\rastermap\gui\io.py", line 71, in load_mat
    X, Usv, Vsv, xy = load_activity(parent.fname)
  File "C:\Users\pseud\anaconda3\envs\rastermap\lib\site-packages\rastermap\io.py", line 111, in load_activity
    if isinstance(X.item(), dict):
ValueError: can only convert an array of size 1 to a Python scalar
```
Is it an issue of backward compatibility with an Suite2P version? Or something else? 
Thanks

**Comment by carsen-stringer** [comment]
sorry about that, it was a bug, please `pip install git+https://github.com/mouseland/rastermap.git`, we will also make a new pip that will deploy soon (then you can `pip install rastermap --upgrade`)

**Comment by carsen-stringer** [comment]
pip is now deployed (`pip install rastermap --upgrade`)

**Comment by vncntprvst** [comment]
Works great! Thank you
