### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by ehennestad** [MouseLand/rastermap#2]
Hi, 

Thanks for some great tools. I just wanted to report that when I have both FaceMap an rastermap on the matlabpath at the same time, I receive the following error (using the mapTmap function): 

Error using reshape
To RESHAPE the number of elements must not change.

Error in my_conv2 (line 47)
    S1 = reshape(S1, dsnew);

Error in activityMap (line 57)
    V = my_conv2(V, sig(t), 2);

Error in mapTmap (line 16)
[~, isort2, ~] = activityMap(S', ops);

**Comment by carsen-stringer** [comment]
we are no longer supporting the matlab version, it is not the same as the paper, please use the python version (it can take as input matlab files)
