### ISSUE TITLE
Problem open suite2p file in rastermap

### ISSUE THREAD

**Issue by ZiTao956** [MouseLand/rastermap#20]
Hello! I have some problems with opening the npy file from the result of suite2p in rastermap, I have tried F.npy and spk.npy, and I have tried load data matrix and load processed data, they all show this 'ValueError: can only convert an array of size 1 to a Python scalar' I also check the libraries, seems all the libraries require are already installed in my conda environment.

Here is the detail of the ValueError:
`Loading C:/Users/Zi/Downloads/test_outputs/test_outputs/1plane1chan1500/suite2p/plane0/F.npy
Traceback (most recent call last):
  File "C:\Users\Zi\.conda\envs\rastermap\lib\site-packages\rastermap\gui\menus.py", line 20, in <lambda>
    loadMat.triggered.connect(lambda: io.load_mat(parent, name=None))
  File "C:\Users\Zi\.conda\envs\rastermap\lib\site-packages\rastermap\gui\io.py", line 71, in load_mat
    X, Usv, Vsv, xy = load_activity(parent.fname)
  File "C:\Users\Zi\.conda\envs\rastermap\lib\site-packages\rastermap\io.py", line 111, in load_activity
    if isinstance(X.item(), dict):
ValueError: can only convert an array of size 1 to a Python scalar`

**Comment by carsen-stringer** [comment]
Sorry about this can you please try the latest version? `pip install rastermap --upgrade`

**Comment by ZiTao956** [comment]
Dear Carsen,
I reinstall rastermap and upgrade to the latest version, and now it works.
Thank you very much:)
Best regards,

Zi
