### ISSUE TITLE
start the rastermap with extracted ROI excel file

### ISSUE THREAD

**Issue by zhouyi0812** [MouseLand/rastermap#22]
Hello!

I wonder can I start the rastermap with the time series data on an Excel file? I already extract the ROI with caiman package with the traces. But it won't have the 'position' and other features like suite2p on your demo data. 
Or it should be fine if I calculate the necessary SVD value and add to the Excel?

So my goal is to sort the trace only without predicting the behavior.

Thank you for your guidance!

**Comment by carsen-stringer** [comment]
You need an array of neurons by fluorescence (npy or mat). Then you can load in the positions as an npy file as well (number of neurons by 2) with an x and y position for each neuron. Or you can explore without the positions. Alternatively if Caiman exports an NWB file you can try that out -- we have support for those types of files.
