### ISSUE TITLE
GUI version for linux or windows?

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/rastermap#26]
Hi,

When do you plan on releasing a version with the GUI that runs on Windows or Linux? This would be very helpful for us, as we don't currently use Apple products in our labs.

Thanks,

Evan

**Comment by carsen-stringer** [comment]
I'm sorry what is the error message on Windows and Linux? I've never actually tested the GUI in Mac (I don't have one) but it works on my Windows laptop and my Linux desktop

**Comment by carsen-stringer** [comment]
Oh I see from the repo:
```
Linux, Windows and Mac OS are supported for running the code. For running the graphical interface you will need a Mac OS later than Yosemite. 
```
should be
```
Linux, Windows and Mac OS are supported for running the code. For running the graphical interface **in Mac** you will need a Mac OS later than Yosemite. 
```

**Comment by carsen-stringer** [comment]
but reopen if you have an install question
