### ISSUE TITLE
associated paper

### ISSUE THREAD

**Issue by vruetten** [MouseLand/rastermap#3]
Hey Marius and Carsen,

Thanks for the cool talk.

I can't seem to find a paper outlining the exact steps you follow to compute the rastermap or comparison with other methods. I'm probably not looking well enough - would you mind posting the link when you have a moment?

Looking forward to better understanding it/testing it out, :) 

Thanks,
Ginny

**Comment by marius10p** [comment]
Hi Virginia, we are still working on the paper, but we'll send you our CoSyNe abstract that has a little more information. - Marius

**Comment by elhananby** [comment]
Hi Marius,
do you have any update about a possible paper/the cosyne abstract? I have a bit of a hard time understanding how to interpret the results of the algorithm.

Thanks

**Comment by Michaelhess17** [comment]
Hi just nudging this in case there has been any update in this regard. My employer wants me to reproduce this code in another language, but it is quite difficult without understanding how the algorithm works in the first place...

**Comment by carsen-stringer** [comment]
the preprint is now available: https://www.biorxiv.org/content/10.1101/2023.07.25.550571v1
