### ISSUE TITLE
request: data preperation function

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/rastermap#32]
there is no documentation on the format of the inputs required. just the file format being .npy / .mat etc.
"load data matrix" doesn't explain what the matrix values are (1/0, or times, or binned firing rate?)

could you post a function that for example reads kilosort output folder / spikeinterface output and saves the files required for rastermap?

thanks,
shahaf

**Comment by carsen-stringer** [comment]
this is requested in issue #27, I'm going to close this and will ping you when I implement it directly soon, in the meantime see the info in that issue for how to bin spiking data (requires loading in your spike times and your cluster ids)

**Comment by carsen-stringer** [comment]
this is now added!
