### ISSUE TITLE
Preferred citation?

### ISSUE THREAD

**Issue by djoshea** [MouseLand/rastermap#8]
HI Carsen,

I've used rastermap in a supplemental figure and I'd like to appropriately credit it. Is there a preferred citation for it? I saw the other issue about a COSYNE abstract, but I wasn't sure whether there is one specifically on rastermap.

Would something like this be appropriate?

> Stringer, C., Pachitariu, M. Rastermap: A multi-dimensional embedding algorithm (2018). _GitHub repository_. https://github.com/MouseLand/rastermap

Thanks so much for your work on this!
Dan

**Comment by carsen-stringer** [comment]
thanks Dan for citing the repo! going forward you can cite the biorxiv preprint
